CREATE DATABASE IF NOT EXISTS main;
USE main;
CREATE TABLE IF NOT EXISTS main (
    id INT NOT NULL AUTO_INCREMENT,
    data TEXT NOT NULL,
    val FLOAT NOT NULL,
    PRIMARY KEY (id)
);

USE main;
LOAD DATA LOCAL INFILE '/data.csv' INTO TABLE main
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
    (data, val);